# Generated by Django 5.1.1 on 2024-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Envio_paq',
            fields=[
                ('id_enviopaq', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto_t', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('peso', models.FloatField(help_text='Peso en kilogramos')),
                ('dimensiones', models.TextField(help_text='longitud, ancho, altiura', max_length=20)),
                ('contenido', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id_realiza', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_tra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=70),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='sin telefono', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
