# Generated by Django 5.1.1 on 2024-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniweb', '0002_envio_envio_paq_factura_paquete_realiza_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=70),
        ),
    ]
